from app.db.table_defs.auth import auth_identities, auth_metadata, auth_refresh_tokens, auth_sessions, auth_users
from app.db.table_defs.public import (
    aspnetroles,
    aspnetuserroles,
    aspnetusers,
    auth_migration_events,
    group_admin_memberships,
    grupper,
    grupper_admin_kobling,
    grupper_kurs_kobling,
    historie,
    historie_kurs,
    kurs,
    nytt_personal,
    paarorende,
    personal,
    personal_bilde,
    personal_fil,
    personal_kort,
    public_metadata,
    registrering,
    user_accounts,
    verv,
    web_sessions,
)
from app.db.table_defs.storage import storage_metadata, storage_objects

__all__ = [
    "aspnetroles",
    "aspnetuserroles",
    "aspnetusers",
    "auth_identities",
    "auth_metadata",
    "auth_migration_events",
    "auth_refresh_tokens",
    "auth_sessions",
    "auth_users",
    "group_admin_memberships",
    "grupper",
    "grupper_admin_kobling",
    "grupper_kurs_kobling",
    "historie",
    "historie_kurs",
    "kurs",
    "nytt_personal",
    "paarorende",
    "personal",
    "personal_bilde",
    "personal_fil",
    "personal_kort",
    "public_metadata",
    "registrering",
    "storage_metadata",
    "storage_objects",
    "user_accounts",
    "verv",
    "web_sessions",
]
